apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-svc
spec:
  type: LoadBalancer
  selector:
    app: k8proj
  ports:
    - name: http
      protocol: TCP
      port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadbalancer-pod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8proj
  template:
    metadata:
      labels:
        app: k8proj 
    spec:
      containers:
        - name: k8cont
          image: fyzalrahman/k8image:latest
          imagePullPolicy: Always
